Update metaflow.yml

diff --git a/.github/workflows/metaflow.yml b/.github/workflows/metaflow.yml
--- a/.github/workflows/metaflow.yml
+++ b/.github/workflows/metaflow.yml
@@ -52,4 +52,4 @@ jobs:
     - name: Show Argo Workflow Logs
       run: |
         echo "Fetching logs for: ${{ env.workflow_name }}"
-        argo logs -n argo ${{ env.workflow_name }} || echo "Workflow may not have logs or failed early."
+        argo logs @latest || echo "Workflow may not have logs or failed early."
