Update metaflow.yml

diff --git a/.github/workflows/metaflow.yml b/.github/workflows/metaflow.yml
--- a/.github/workflows/metaflow.yml
+++ b/.github/workflows/metaflow.yml
@@ -47,9 +47,10 @@ jobs:
         gunzip argo-linux-amd64.gz
         chmod +x argo-linux-amd64 && mv argo-linux-amd64 /usr/local/bin/argo
         aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.EKS_CLUSTER_NAME }}
-        argo submit -n argo argo-metaflow.yaml --serviceaccount argo --watch
+        export WORKFLOW_NAME=$(argo submit -n argo argo-metaflow.yaml --serviceaccount argo --output name)
+        echo "workflow_name=$WORKFLOW_NAME" >> $GITHUB_ENV
         
     - name: Show Argo Workflow Logs
       run: |
-        echo "Fetching logs for: ${{ env.workflow_name }}"
-        argo logs @latest || echo "Workflow may not have logs or failed early."
+        echo "Fetching logs for: $workflow_name"
+        argo logs -n argo "$workflow_name" || echo "Workflow may not have logs or failed early."
